// -----------------------------------------------------------------------------
// Deterministic responses for every non-happy path.
//
// These strings are constants, never generated by the model. That is the whole
// point: when a lookup fails, times out, or the caller goes off-script, the
// words the caller hears are fixed, reviewed, and identical every time. A model
// improvising an apology is a model that can hallucinate a shipping date.
//
// The exact fallback and handoff wording is fixed by AGENTS.md — do not
// paraphrase it.
// -----------------------------------------------------------------------------

import type { OrderResult } from "../tools/order-status.js";

/**
 * Spoken when the lookup fails or times out. Only promises what the system can
 * actually do: this agent does not send SMS, email, or callbacks, so it doesn't
 * offer them. It directs the caller to support without claiming to perform an
 * action it can't (a tool-failure fallback does not transfer — see the
 * architecture note in the README).
 */
export const FALLBACK_RESPONSE =
  "I'm having trouble retrieving that order right now. Please try again later, or " +
  "contact our support team and they can help.";

/** Spoken for any out-of-scope request (billing, returns, disputes, etc.). */
export const HANDOFF_RESPONSE =
  "That's something our support team handles directly. Let me connect you now.";

/** Spoken when the caller has not yet provided an order number. */
export const ASK_FOR_ORDER_NUMBER =
  "Sure, I can check that for you. What's your order number?";

/**
 * The agent's opening line, spoken as soon as Deepgram is ready (on
 * SettingsApplied). Deterministic on purpose — the caller needs a clear cue
 * that the agent is listening, and a fixed greeting keeps the very first thing
 * the caller hears reviewed rather than model-improvised. It also states the
 * one thing this agent does, so out-of-scope asks are less likely.
 */
export const GREETING =
  "Hi, you've reached the order status line. I can check the status of an order " +
  "for you — what's your order number?";

/**
 * Group the deterministic strings so callers can reference them as one unit and
 * so the set is easy to audit in one place.
 */
export const CANNED_RESPONSES = {
  greeting: GREETING,
  fallback: FALLBACK_RESPONSE,
  handoff: HANDOFF_RESPONSE,
  askForOrderNumber: ASK_FOR_ORDER_NUMBER,
} as const;

/**
 * Render a *successful* order result into one or two natural spoken sentences.
 *
 * This deliberately covers only `in_transit` and `delivered` — the two outcomes
 * the agent reads back. `not_found` and `error` are failure modes: the caller
 * hears the fallback, not a description of the failure. Callers must branch on
 * status before reaching here; passing a failure status is a programming error.
 */
export function describeOrderResult(result: OrderResult): string {
  switch (result.status) {
    case "in_transit":
      return `Good news — your order is on its way and is estimated to arrive on ${formatDate(
        result.estimatedDelivery,
      )}.`;
    case "delivered":
      return `That order was delivered on ${formatDate(result.deliveredAt)}.`;
    case "not_found":
    case "error":
      throw new Error(
        `describeOrderResult should not be called for a "${result.status}" result — ` +
          "use FALLBACK_RESPONSE instead.",
      );
  }
}

/**
 * Format an ISO date (or datetime) into a spoken-friendly form, e.g.
 * "July 29, 2026". Falls back to the raw string if it cannot be parsed, so a
 * malformed date never crashes a live call.
 */
function formatDate(iso: string): string {
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) return iso;
  return parsed.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}
